Add pull request file change limit check to CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,9 +7,36 @@ on:
       - cdot-release*
   pull_request:
     branches:
-      - '**' # Run on PRs to any branch
+      - "**" # Run on PRs to any branch
 
 jobs:
+  test_change_limit:
+    if: github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout ${{ github.event.repository.name }}
+        uses: actions/checkout@v4
+
+      - name: Get changed files
+        id: changed-files
+        uses: step-security/changed-files@v46
+
+      - name: Check for large changes
+        env:
+          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
+        run: |
+          # Check the number of changed files in the pull request
+          CHANGED_FILES_COUNT=$(echo "$ALL_CHANGED_FILES" | wc -w)
+
+          echo "Changed files: $CHANGED_FILES_COUNT"
+            # Set MAX_CHANGED_FILES from env or default to 25
+            MAX_CHANGED_FILES="${{ vars.MAX_CHANGED_FILES || 25 }}"
+
+            if [ "$CHANGED_FILES_COUNT" -gt "$MAX_CHANGED_FILES" ]; then
+            echo "Error: Pull request has more than $MAX_CHANGED_FILES changed files. Please reduce the size of your changes."
+            exit 1
+          fi
+
   build_api:
     runs-on: ubuntu-latest
     container:
@@ -95,8 +122,8 @@ jobs:
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
-          distribution: 'adopt'
-          java-version: '21'
+          distribution: "adopt"
+          java-version: "21"
 
       - name: Build and Test with Maven
         run: |
@@ -131,7 +158,7 @@ jobs:
       - name: Install Dependencies
         env:
           MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
-          MAVEN_GITHUB_ORG: 'usdot-jpo-ode'
+          MAVEN_GITHUB_ORG: "usdot-jpo-ode"
         run: |
           cd $GITHUB_WORKSPACE/services/intersection-api/api
           mvn clean install -DskipTests -s ./settings.xml
@@ -140,7 +167,7 @@ jobs:
       - name: Run tests
         env:
           MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
-          MAVEN_GITHUB_ORG: 'usdot-jpo-ode'
+          MAVEN_GITHUB_ORG: "usdot-jpo-ode"
         run: |
           cd $GITHUB_WORKSPACE/services/intersection-api/api
           mvn verify -s ./settings.xml
@@ -189,8 +216,8 @@ jobs:
 
       - uses: actions/setup-java@v4
         with:
-          distribution: 'temurin'
-          java-version: '17'
+          distribution: "temurin"
+          java-version: "17"
 
       - name: Setup SonarScanner
         uses: warchant/setup-sonar-scanner@v7
